/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/usuarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_usuarios_get"];
        put?: never;
        /** Create User */
        post: operations["create_user_usuarios_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usuarios/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Deactivate User */
        delete: operations["deactivate_user_usuarios__user_id__delete"];
        options?: never;
        head?: never;
        /** Update User */
        patch: operations["update_user_usuarios__user_id__patch"];
        trace?: never;
    };
    "/catalog/areas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Areas */
        get: operations["list_areas_catalog_areas_get"];
        put?: never;
        /** Create Area */
        post: operations["create_area_catalog_areas_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Categories */
        get: operations["list_categories_catalog_categories_get"];
        put?: never;
        /** Create Category */
        post: operations["create_category_catalog_categories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/specialties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Specialties */
        get: operations["list_specialties_catalog_specialties_get"];
        put?: never;
        /** Create Specialty */
        post: operations["create_specialty_catalog_specialties_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/shifts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Shifts */
        get: operations["list_shifts_catalog_shifts_get"];
        put?: never;
        /** Create Shift */
        post: operations["create_shift_catalog_shifts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/technicians": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Technicians */
        get: operations["list_technicians_catalog_technicians_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/technicians/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Technician */
        patch: operations["update_technician_catalog_technicians__user_id__patch"];
        trace?: never;
    };
    "/solicitudes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Request */
        post: operations["create_request_solicitudes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sla/agreements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Agreements */
        get: operations["list_agreements_sla_agreements_get"];
        put?: never;
        /** Create Agreement */
        post: operations["create_agreement_sla_agreements_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sla/agreements/{agreement_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Versions */
        get: operations["list_versions_sla_agreements__agreement_id__versions_get"];
        put?: never;
        /** Publish Version */
        post: operations["publish_version_sla_agreements__agreement_id__versions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sla/effective": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Effective Sla */
        get: operations["get_effective_sla_sla_effective_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CategoryCreate */
        CategoryCreate: {
            /**
             * Area Id
             * Format: uuid
             */
            area_id: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
        };
        /** CategoryRead */
        CategoryRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Area Id
             * Format: uuid
             */
            area_id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Is Active */
            is_active: boolean;
        };
        /**
         * EffectiveSlaRead
         * @description Acuerdo que aplica a una categoría y prioridad en una fecha dada.
         */
        EffectiveSlaRead: {
            /**
             * Agreement Id
             * Format: uuid
             */
            agreement_id: string;
            /** Agreement Name */
            agreement_name: string;
            /** Version */
            version: number;
            priority: components["schemas"]["Priority"];
            /** First Response Minutes */
            first_response_minutes: number;
            /** Resolution Minutes */
            resolution_minutes: number;
            /**
             * Valid From
             * Format: date-time
             */
            valid_from: string;
            /** Used Default */
            used_default: boolean;
            /** Notice */
            notice: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Priority
         * @enum {string}
         */
        Priority: "P1" | "P2" | "P3" | "P4";
        /**
         * RequestChannel
         * @enum {string}
         */
        RequestChannel: "portal" | "phone" | "in_person";
        /**
         * RequestCreate
         * @description Fields accepted when a requester submits a new service request.
         */
        RequestCreate: {
            /**
             * Requester Id
             * Format: uuid
             */
            requester_id: string;
            /** Category Id */
            category_id?: string | null;
            /** Asset Id */
            asset_id?: string | null;
            /** Related Request Id */
            related_request_id?: string | null;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Physical Location */
            physical_location: string;
            /** @default portal */
            channel: components["schemas"]["RequestChannel"];
            /** Urgency */
            urgency?: number | null;
            /** Impact */
            impact?: number | null;
        };
        /**
         * RequestRead
         * @description Public representation of a service request returned by the API.
         */
        RequestRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Requester Id
             * Format: uuid
             */
            requester_id: string;
            /** Category Id */
            category_id: string | null;
            /** Asset Id */
            asset_id: string | null;
            /** Service Level Version Id */
            service_level_version_id: string | null;
            /** Related Request Id */
            related_request_id: string | null;
            /** Folio */
            folio: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Physical Location */
            physical_location: string;
            channel: components["schemas"]["RequestChannel"];
            status: components["schemas"]["RequestStatus"];
            priority: components["schemas"]["Priority"] | null;
            /** Urgency */
            urgency: number | null;
            /** Impact */
            impact: number | null;
            /** Classification Confidence */
            classification_confidence: number | null;
            /** First Response At */
            first_response_at: string | null;
            /** Resolved At */
            resolved_at: string | null;
            /** Closed At */
            closed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * RequestStatus
         * @enum {string}
         */
        RequestStatus: "registered" | "classified" | "pending_review" | "assigned" | "in_progress" | "waiting" | "escalated" | "resolved" | "closed" | "closed_unverified";
        /**
         * RoleName
         * @enum {string}
         */
        RoleName: "administrator" | "service_manager" | "support_agent" | "classifier" | "knowledge_manager" | "auditor" | "requester";
        /** ServiceAreaCreate */
        ServiceAreaCreate: {
            /**
             * Unit Id
             * Format: uuid
             */
            unit_id: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
        };
        /** ServiceAreaRead */
        ServiceAreaRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Unit Id
             * Format: uuid
             */
            unit_id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Is Active */
            is_active: boolean;
        };
        /**
         * ShiftCreate
         * @description Shift expressed in minutes from midnight (e.g. 07:00 = 420).
         */
        ShiftCreate: {
            /** Name */
            name: string;
            /** Start Minute */
            start_minute: number;
            /** End Minute */
            end_minute: number;
        };
        /** ShiftRead */
        ShiftRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Start Minute */
            start_minute: number;
            /** End Minute */
            end_minute: number;
            /** Is Active */
            is_active: boolean;
        };
        /**
         * SlaAgreementCreate
         * @description Acuerdo de nivel de servicio: de una categoría o el predeterminado.
         */
        SlaAgreementCreate: {
            /** Name */
            name: string;
            /** Category Id */
            category_id?: string | null;
            /**
             * Is Default
             * @default false
             */
            is_default: boolean;
        };
        /** SlaAgreementRead */
        SlaAgreementRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Category Id */
            category_id: string | null;
            /** Name */
            name: string;
            /** Is Default */
            is_default: boolean;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * SlaPriorityTimes
         * @description Tiempos comprometidos para una prioridad, en minutos.
         */
        SlaPriorityTimes: {
            priority: components["schemas"]["Priority"];
            /** First Response Minutes */
            first_response_minutes: number;
            /** Resolution Minutes */
            resolution_minutes: number;
        };
        /**
         * SlaVersionCreate
         * @description Nueva versión del acuerdo, con su fecha de entrada en vigor.
         */
        SlaVersionCreate: {
            /**
             * Valid From
             * Format: date-time
             */
            valid_from: string;
            /** Times */
            times: components["schemas"]["SlaPriorityTimes"][];
        };
        /** SlaVersionRead */
        SlaVersionRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Agreement Id
             * Format: uuid
             */
            agreement_id: string;
            /** Version */
            version: number;
            priority: components["schemas"]["Priority"];
            /** First Response Minutes */
            first_response_minutes: number;
            /** Resolution Minutes */
            resolution_minutes: number;
            /**
             * Valid From
             * Format: date-time
             */
            valid_from: string;
            /** Valid To */
            valid_to: string | null;
        };
        /** SpecialtyCreate */
        SpecialtyCreate: {
            /**
             * Category Id
             * Format: uuid
             */
            category_id: string;
            /** Name */
            name: string;
        };
        /** SpecialtyRead */
        SpecialtyRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Category Id
             * Format: uuid
             */
            category_id: string;
            /** Name */
            name: string;
            /** Is Active */
            is_active: boolean;
        };
        /**
         * SupportLevel
         * @enum {string}
         */
        SupportLevel: "level_1" | "level_2";
        /**
         * TechnicianProfileUpdate
         * @description Mutable technician attributes used by the assignment engine (RN-08).
         */
        TechnicianProfileUpdate: {
            support_level?: components["schemas"]["SupportLevel"] | null;
            /** Shift Id */
            shift_id?: string | null;
            /** Max Load */
            max_load?: number | null;
            /** Specialty Ids */
            specialty_ids?: string[] | null;
        };
        /** TechnicianRead */
        TechnicianRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Full Name */
            full_name: string;
            support_level: components["schemas"]["SupportLevel"] | null;
            /** Shift Id */
            shift_id: string | null;
            /** Max Load */
            max_load: number | null;
            /** Is Active */
            is_active: boolean;
            /** Specialty Ids */
            specialty_ids: string[];
        };
        /**
         * UserCreate
         * @description Fields accepted when provisioning a new account from the directory.
         */
        UserCreate: {
            /** Institutional Id */
            institutional_id: string;
            role: components["schemas"]["RoleName"];
            /** Unit Id */
            unit_id?: string | null;
            /** Max Load */
            max_load?: number | null;
        };
        /**
         * UserRead
         * @description Public representation of a user account, with roles flattened to their names.
         */
        UserRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Institutional Id */
            institutional_id: string;
            /** Full Name */
            full_name: string;
            /** Email */
            email: string;
            user_type: components["schemas"]["UserType"];
            support_level: components["schemas"]["SupportLevel"] | null;
            /** Is Active */
            is_active: boolean;
            /** Max Load */
            max_load: number | null;
            /** Roles */
            roles: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * UserType
         * @enum {string}
         */
        UserType: "student" | "academic" | "administrative" | "technical";
        /**
         * UserUpdate
         * @description Fields that can be modified on an existing account.
         *
         *     Only fields explicitly sent by the client are applied (ver `exclude_unset`
         *     en el servicio); omitir un campo lo deja sin cambios, mientras que enviarlo
         *     explícitamente como `null` lo limpia.
         */
        UserUpdate: {
            role?: components["schemas"]["RoleName"] | null;
            /** Unit Id */
            unit_id?: string | null;
            /** Max Load */
            max_load?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_users_usuarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"][];
                };
            };
        };
    };
    create_user_usuarios_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deactivate_user_usuarios__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_usuarios__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_areas_catalog_areas_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceAreaRead"][];
                };
            };
        };
    };
    create_area_catalog_areas_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServiceAreaCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceAreaRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_categories_catalog_categories_get: {
        parameters: {
            query?: {
                area_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_category_catalog_categories_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_specialties_catalog_specialties_get: {
        parameters: {
            query?: {
                category_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecialtyRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_specialty_catalog_specialties_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpecialtyCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecialtyRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_shifts_catalog_shifts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShiftRead"][];
                };
            };
        };
    };
    create_shift_catalog_shifts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShiftCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShiftRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_technicians_catalog_technicians_get: {
        parameters: {
            query?: {
                specialty_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TechnicianRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_technician_catalog_technicians__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TechnicianProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TechnicianRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_request_solicitudes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_agreements_sla_agreements_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlaAgreementRead"][];
                };
            };
        };
    };
    create_agreement_sla_agreements_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SlaAgreementCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlaAgreementRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_versions_sla_agreements__agreement_id__versions_get: {
        parameters: {
            query?: {
                priority?: components["schemas"]["Priority"] | null;
            };
            header?: never;
            path: {
                agreement_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlaVersionRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_version_sla_agreements__agreement_id__versions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agreement_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SlaVersionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlaVersionRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_effective_sla_sla_effective_get: {
        parameters: {
            query: {
                priority: components["schemas"]["Priority"];
                category_id?: string | null;
                at?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EffectiveSlaRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
