"""Initial migration

Revision ID: 744530feb03d
Revises: 
Create Date: 2026-09-20 18:10:16.004214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '744530feb03d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('educational_programs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('level', sa.String(length=60), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('model_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.String(length=60), nullable=False),
    sa.Column('artifact_uri', sa.String(length=300), nullable=True),
    sa.Column('accuracy', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('notification_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_code', sa.String(length=80), nullable=False),
    sa.Column('subject_template', sa.String(length=240), nullable=False),
    sa.Column('body_template', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_code')
    )
    op.create_table('organizational_units',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('unit_type', sa.String(length=60), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['organizational_units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=240), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('shifts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('start_minute', sa.Integer(), nullable=False),
    sa.Column('end_minute', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('physical_spaces',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('unit_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('building', sa.String(length=120), nullable=False),
    sa.Column('space_type', sa.String(length=50), nullable=False),
    sa.Column('class_schedule', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['organizational_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_areas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('unit_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['organizational_units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('unit_id', sa.Uuid(), nullable=True),
    sa.Column('institutional_id', sa.String(length=80), nullable=False),
    sa.Column('full_name', sa.String(length=180), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('user_type', sa.String(length=30), nullable=False),
    sa.Column('support_level', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('max_load', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['organizational_units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_institutional_id'), 'users', ['institutional_id'], unique=True)
    op.create_table('academic_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('program_id', sa.Uuid(), nullable=False),
    sa.Column('enrollment_number', sa.String(length=60), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['educational_programs.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enrollment_number')
    )
    op.create_table('assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('space_id', sa.Uuid(), nullable=True),
    sa.Column('identifier', sa.String(length=80), nullable=False),
    sa.Column('asset_type', sa.String(length=80), nullable=False),
    sa.Column('brand', sa.String(length=80), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('serial_number', sa.String(length=120), nullable=True),
    sa.Column('institutional_inventory_number', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=35), nullable=False),
    sa.Column('physical_condition', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['space_id'], ['physical_spaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier'),
    sa.UniqueConstraint('institutional_inventory_number'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=80), nullable=False),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('area_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['service_areas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('maintenance_orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('space_id', sa.Uuid(), nullable=False),
    sa.Column('responsible_id', sa.Uuid(), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('maintenance_type', sa.String(length=20), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['responsible_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['space_id'], ['physical_spaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_role')
    )
    op.create_table('asset_custodies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('custodian_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_at', sa.Date(), nullable=False),
    sa.Column('returned_at', sa.Date(), nullable=True),
    sa.Column('acceptance_signature', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['custodian_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_custodies_asset_id'), 'asset_custodies', ['asset_id'], unique=False)
    op.create_table('knowledge_articles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('symptom', sa.Text(), nullable=False),
    sa.Column('cause', sa.Text(), nullable=False),
    sa.Column('procedure', sa.Text(), nullable=False),
    sa.Column('verification', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_acts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('technician_id', sa.Uuid(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('parts_used', sa.Text(), nullable=True),
    sa.Column('execution_signature', sa.Text(), nullable=True),
    sa.Column('conformity_signature', sa.Text(), nullable=True),
    sa.Column('next_maintenance_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['maintenance_orders.id'], ),
    sa.ForeignKeyConstraint(['technician_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_level_agreements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specialties',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'name', name='uq_specialty_category_name')
    )
    op.create_table('service_level_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agreement_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=2), nullable=False),
    sa.Column('first_response_minutes', sa.Integer(), nullable=False),
    sa.Column('resolution_minutes', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agreement_id'], ['service_level_agreements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agreement_id', 'version', name='uq_sla_version')
    )
    op.create_table('service_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('requester_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('service_level_version_id', sa.Uuid(), nullable=True),
    sa.Column('related_request_id', sa.Uuid(), nullable=True),
    sa.Column('folio', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('physical_location', sa.String(length=240), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.String(length=2), nullable=True),
    sa.Column('urgency', sa.Integer(), nullable=True),
    sa.Column('impact', sa.Integer(), nullable=True),
    sa.Column('classification_confidence', sa.Float(), nullable=True),
    sa.Column('first_response_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['related_request_id'], ['service_requests.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['service_level_version_id'], ['service_level_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_requests_folio'), 'service_requests', ['folio'], unique=True)
    op.create_index(op.f('ix_service_requests_requester_id'), 'service_requests', ['requester_id'], unique=False)
    op.create_table('classification_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('model_version_id', sa.Uuid(), nullable=True),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('urgency', sa.Integer(), nullable=False),
    sa.Column('impact', sa.Integer(), nullable=False),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['service_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classification_results_request_id'), 'classification_results', ['request_id'], unique=False)
    op.create_table('knowledge_searches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('article_id', sa.Uuid(), nullable=True),
    sa.Column('request_id', sa.Uuid(), nullable=True),
    sa.Column('searched_by_id', sa.Uuid(), nullable=False),
    sa.Column('query', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['knowledge_articles.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['service_requests.id'], ),
    sa.ForeignKeyConstraint(['searched_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=True),
    sa.Column('request_id', sa.Uuid(), nullable=True),
    sa.Column('recipient_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('subject', sa.String(length=240), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['service_requests.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['notification_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request_assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('technician_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('score_breakdown', sa.Text(), nullable=True),
    sa.Column('is_automatic', sa.Boolean(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('unassigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['service_requests.id'], ),
    sa.ForeignKeyConstraint(['technician_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_assignments_request_id'), 'request_assignments', ['request_id'], unique=False)
    op.create_table('request_escalations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by_id', sa.Uuid(), nullable=False),
    sa.Column('approved_by_id', sa.Uuid(), nullable=True),
    sa.Column('escalation_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['service_requests.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_escalations_request_id'), 'request_escalations', ['request_id'], unique=False)
    op.create_table('request_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('previous_status', sa.String(length=30), nullable=True),
    sa.Column('new_status', sa.String(length=30), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['service_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_logs_request_id'), 'request_logs', ['request_id'], unique=False)
    op.create_table('classification_corrections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('result_id', sa.Uuid(), nullable=False),
    sa.Column('corrected_by_id', sa.Uuid(), nullable=False),
    sa.Column('corrected_category_id', sa.Uuid(), nullable=True),
    sa.Column('corrected_urgency', sa.Integer(), nullable=True),
    sa.Column('corrected_impact', sa.Integer(), nullable=True),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['corrected_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['corrected_category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['result_id'], ['classification_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('classification_corrections')
    op.drop_index(op.f('ix_request_logs_request_id'), table_name='request_logs')
    op.drop_table('request_logs')
    op.drop_index(op.f('ix_request_escalations_request_id'), table_name='request_escalations')
    op.drop_table('request_escalations')
    op.drop_index(op.f('ix_request_assignments_request_id'), table_name='request_assignments')
    op.drop_table('request_assignments')
    op.drop_table('notifications')
    op.drop_table('knowledge_searches')
    op.drop_index(op.f('ix_classification_results_request_id'), table_name='classification_results')
    op.drop_table('classification_results')
    op.drop_index(op.f('ix_service_requests_requester_id'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_folio'), table_name='service_requests')
    op.drop_table('service_requests')
    op.drop_table('service_level_versions')
    op.drop_table('specialties')
    op.drop_table('service_level_agreements')
    op.drop_table('maintenance_acts')
    op.drop_table('knowledge_articles')
    op.drop_index(op.f('ix_asset_custodies_asset_id'), table_name='asset_custodies')
    op.drop_table('asset_custodies')
    op.drop_table('user_roles')
    op.drop_table('maintenance_orders')
    op.drop_table('categories')
    op.drop_table('audit_logs')
    op.drop_table('assets')
    op.drop_table('academic_records')
    op.drop_index(op.f('ix_users_institutional_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('service_areas')
    op.drop_table('physical_spaces')
    op.drop_table('shifts')
    op.drop_table('roles')
    op.drop_table('organizational_units')
    op.drop_table('notification_templates')
    op.drop_table('model_versions')
    op.drop_table('educational_programs')
    # ### end Alembic commands ###
